### PR TITLE
[tcp] Don't Reset too Early while Establishing Connection

### PR DESCRIPTION
**Pull request by ppenna**
Description
========

Changing the code to be conformant to [RFC 793 Section 3.4](https://datatracker.ietf.org/doc/html/rfc793#section-3.4):

> In all states except SYN-SENT, all reset (RST) segments are validated
  by checking their SEQ-fields.  A reset is valid if its sequence number
  is in the window.  In the SYN-SENT state (a RST received in response
  to an initial SYN), the RST is acceptable if the ACK field
  acknowledges the SYN.

### CODE REVIEW

**Review by BrianZill — CHANGES_REQUESTED** [review]
You can't just move the reset handling to after the check for an incoming SYN+ACK, because a valid RST just needs to be a valid ACK of our SYN -- it doesn't need to be (and probably won't be) a SYN itself.  So as is, this change would drop valid RSTs, rather than act on them.  You probably want to verify that the ACK is valid, then see if it is a RST, then verify that it is a SYN.

There is still another (different) bug here though.  In SYN-ACK state we're also supposed to handle receiving just a SYN (without an ACK of our SYN) -- this is the simultaneous open case.  But that's a corner case we can probably skip supporting for now.

**Comment by ppenna** [comment]
> You can't just move the reset handling to after the check for an incoming SYN+ACK, because a valid RST just needs to be a valid ACK of our SYN -- it doesn't need to be (and probably won't be) a SYN itself. So as is, this change would drop valid RSTs, rather than act on them. You probably want to verify that the ACK is valid, then see if it is a RST, then verify that it is a SYN.
> 
> There is still another (different) bug here though. In SYN-ACK state we're also supposed to handle receiving just a SYN (without an ACK of our SYN) -- this is the simultaneous open case. But that's a corner case we can probably skip supporting for now.

I've patched my fix to reflect the first point. Let me know if it is ok now.

Concerning the second one, I'd rather fix on a different PR.

**Review by BrianZill — CHANGES_REQUESTED** [review]
These are now the right checks in the right order, but the wrong actions.  Basically, delete line 113  and line 125.  Here's the rationale: for the first check, only packets with a valid ACK should be accepted.  Any other packets with the five-tuple for this connection should be dropped (i.e. ignored) -- as they are either old packets for a previous incarnation of this connection or a deliberate attempt to DoS us -- but they shouldn't affect our current connection attempt.  We don't want to close this connection with a ConnectionRefused here (that's just what an attacker would want).  So take out line 113.  For the second check, a RST coming back (which we now know has the right ACK information) is exactly what we'd expect the other side to send if it isn't accepting connections on that port, so line 119 is right -- close the connection with a ConnectionRefused error to the user.  For the third check, getting an ACK for our SYN that isn't a SYN itself is weird.  Our peer is saying "yeah, I got that you want to talk to me, and I'm not going to refuse your request, but I'm not going to tell you I want to talk to you either".  Normally a TCP wouldn't send such a packet, and it doesn't affect our state in any way, so we should just drop (ignore) it.  Maybe our peer will get around to sending us a SYN before we timeout.  But again, we don't want to close the connection with a ConnectionRefused in this case.  So remove line 125.

I'd also change the comment on line 117 to say something like "Check if our peer is refusing our connection request."  Or something like that.

Other than that, this looks good.

**Comment by ppenna** [comment]
> These are now the right checks in the right order, but the wrong actions. Basically, delete line 113 and line 125. Here's the rationale: for the first check, only packets with a valid ACK should be accepted. Any other packets with the five-tuple for this connection should be dropped (i.e. ignored) -- as they are either old packets for a previous incarnation of this connection or a deliberate attempt to DoS us -- but they shouldn't affect our current connection attempt. We don't want to close this connection with a ConnectionRefused here (that's just what an attacker would want). So take out line 113. For the second check, a RST coming back (which we now know has the right ACK information) is exactly what we'd expect the other side to send if it isn't accepting connections on that port, so line 119 is right -- close the connection with a ConnectionRefused error to the user. For the third check, getting an ACK for our SYN that isn't a SYN itself is weird. Our peer is saying "yeah, I got that you want to talk to me, and I'm not going to refuse your request, but I'm not going to tell you I want to talk to you either". Normally a TCP wouldn't send such a packet, and it doesn't affect our state in any way, so we should just drop (ignore) it. Maybe our peer will get around to sending us a SYN before we timeout. But again, we don't want to close the connection with a ConnectionRefused in this case. So remove line 125.
> 
> I'd also change the comment on line 117 to say something like "Check if our peer is refusing our connection request." Or something like that.
> 
> Other than that, this looks good.

Hello Brian, thanks for the rationale. I just fix these final issues.

**Review by BrianZill — APPROVED** [review]
Looks good!

**Pull request merged**
